### ISSUE TITLE
SuspiciousOperation at /offline/: Attempted access to '/css/django-pwa-app.css' denied.

### ISSUE THREAD

**Issue by ishtiaque06** [silviolleite/django-pwa#12]
Hello! I have been playing around with my django app and testing it out in my staging server. I just set up an external DigitalOcean Spaces storage to serve up my static files (very similar to Amazon S3). As it turns out, this caused a new problem in my codebase which originated from django-pwa's `offline.html` file. A screenshot is attached below. 

![Screenshot from 2019-05-05 06-50-56](https://user-images.githubusercontent.com/10186660/57192810-94e27e80-6f02-11e9-9e90-91692f537e02.png)

My speculation is that this should not be happening since clearly the request is trying to access `/css/django-pwa-app.css` whereas in reality it should not be requesting files from '/'. I think this is a typo and can be fixed easily, but if it's not and I need a better understanding of how the static file serving works, please let me know! 

I do know that I can just use my own `offline.html` file but posting this here in case other people face the same issue. 

Best,
Ahmed

**Comment by silviolleite** [comment]
@ishtiaque06, Have you solved it?

**Comment by ishtiaque06** [comment]
I think I found a workaround but forgot what it was :(

**Comment by PiusLucky** [comment]
Am a little late to the party.
The **django-pwa-app.css** is not properly linked.
Go to your specific HTML and:

Replace:

`<link href="{% static '/css/django-pwa-app.css' %}"`

With:

`<link href="{% static 'css/django-pwa-app.css' %}"`

The culprit was the **"/"** added at the beginning of the CSS url.
