### ISSUE TITLE
Error installing in Divio project

### ISSUE THREAD

**Issue by BradleyKirton** [silviolleite/django-pwa#13]
Hi there thanks for the awesome project.

I am trying to add this application to a [Divio](https://control.divio.com/) project and am getting a ModuleNotFoundError: No module named 'pypandoc'.

I think this may be because Divio is using docker and the with that particular image pip is trying to build the package and pandoc is not available (It is not available on the repo in the image, I could probably work around this and install it).

My question is what was the initial purpose of catching the RuntimeError below and would you be happy I make a PR that catches both RuntimeError and ModuleNotFoundError?

setup.py
```python
# noinspection PyBroadException
try:
    # noinspection PyPackageRequirements
    import pypandoc

    long_description = pypandoc.convert('README.md', 'rst')
except RuntimeError:
    long_description = short_description
```

**Comment by silviolleite** [comment]
Hello @BradleyKirton Did you install the project dependences? There is a file called `requirements-dev.txt` inside the root path with two dependences, `pypandoc==1.3.3` and `tox==3.2.1`.

**Comment by BradleyKirton** [comment]
Hi @silviolleite on the Divio platform I get the error when pip installs the the `django-pwa` library. Divio applications use a docker image that they maintain `divio/base:4.15-py3.6-slim-stretch`.

I think it may be because it is not installing the wheel and it attempts to build from source. I am going to investigate further this evening and I will let you know if I have success.
