### ISSUE TITLE
/offline not redirecting when offline on on Chrome

### ISSUE THREAD

**Issue by jamesmgg** [silviolleite/django-pwa#14]
Produces the following warning:
`The FetchEvent for "http://localhost:8000/" resulted in a network error response: a redirected response was used for a request whose redirect mode is not "follow".`

The issue is that it's caching the redirect url `/offline` the fix is to instead cache `/offline/`
I'll attach a PR with the fix for it.

**Comment by ZippoLag** [comment]
Didn't this get fixed when the PR was merged? Shouldn't it be closed?

**Comment by jamesmgg** [comment]
yes, this got fixed. the ticket was not autoclosed, so closing it now
