### ISSUE TITLE
Installing from git

### ISSUE THREAD

**Issue by isik-kaplan** [silviolleite/django-pwa#18]
Hi there,

After seeing that https://github.com/silviolleite/django-pwa/issues/10 is closed, I wanted to install it from directly git since it has not been yet released to pypi and realized that I can't, because setup.py tries to catch `RuntimeError` instead of `ModuleNotFoundError`, https://github.com/silviolleite/django-pwa/blob/6ba28177ce16a73a7f047b0a9bbc56c26248f6b6/setup.py#L8-L14 which is not a subclass of RuntimeError, when importing `pypandoc`. I think this is a mistake since descriptions are not all that important(I think) for the actual installation of the library.

Also, I'd love to learn if you are planning a new release. 

Thanks!

**Comment by silviolleite** [comment]
Done! It was fixed! Thanks
