### ISSUE TITLE
"Not Found: /serviceworker.js" err after uninstalling

### ISSUE THREAD

**Issue by pnaylor** [silviolleite/django-pwa#2]
After switching to a branch without the this module included and uninstalling it from pip, I am still getting a "Not Found: /serviceworker.js" error on "GET /serviceworker.js HTTP/1.1 404". Not sure where this is getting called from anymore or how to get past it, seems like it must have been caused by this module somehow though. Still want to use this, just having to switch back an forth before it is fully integrated.

Thanks

**Comment by silviolleite** [comment]
Hello @pnaylor, I think it is a browser cache. Did you clean it?

**Comment by silviolleite** [comment]
If you are using the Mozilla Firefox you can unregister the 'serviceworkers' opening a new browser tab and puting this in url address `about:serviceworkers`.

**Comment by pnaylor** [comment]
Thank you @silviolleite, unregistering the worker worked!
