### ISSUE TITLE
The CSS file 'css/django-pwa-app.css' references a file which could not be found

### ISSUE THREAD

**Issue by dennohpeter** [silviolleite/django-pwa#22]
Anyway to get around this without using bootstrap?

more details

> Whitenoise.storage.MissingFileError: The file 'fonts/bootstrap/glyphicons-halflings-regular.eot' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fb5b8567790>.
> 
> The CSS file 'css/django-pwa-app.css' references a file which could not be found:
>   fonts/bootstrap/glyphicons-halflings-regular.eot
> 
> Please check the URL references in this CSS file, particularly any
> relative paths which might be pointing to the wrong location.

**Comment by dennohpeter** [comment]
For me I had to generate custom bootstrap for glyphicons only at 
https://getbootstrap.com/customize/  
I selected Glyphicons as the only option then copied it to my `static` folder under `fonts/bootstrap/`

**Comment by silviolleite** [comment]
@dennohpeter, Have you solved it?

**Comment by dennohpeter** [comment]
Yeah by doing as I said above, it's not like the real solution but that was my workaround

**Comment by silviolleite** [comment]
@dennohpeter My bad loool I am getting crazy.
