### ISSUE TITLE
request.FILES is empty when uploading a file

### ISSUE THREAD

**Issue by tominaga443** [silviolleite/django-pwa#25]
When uploading a file with the form, in the views, `reuqest.FILES` is empty and `request.META['CONTENT_LENGTH'] = 0`.

**Comment by silviolleite** [comment]
It is not related with `django-pwa`.

Try access this link >>> [Django docs - file upload](https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/)

I hope it can help you.
