### ISSUE TITLE
Default serviceworker not handling logout?

### ISSUE THREAD

**Issue by pnaylor** [silviolleite/django-pwa#3]
When I try logging out from a user with this installed (using default serviceworker) it doesn't seem to register the logout and just redirects to the default root page for a user at '/'. This is regardless of my settings value for LOGOUT_REDIRECT_URL or adding a login_url value to logout_then_login(request, '/login/'). The issue goes away if I unregister the serviceworker.

**Comment by silviolleite** [comment]
Hello @pnaylor, are you trying to logout with internet on?  If yes, it isn't using the serviceworker, but if No you should include the logout url in  files To Cache on your custom servicework.js.

**Comment by pnaylor** [comment]
Thanks @silviolleite, it is online and on further testing only seems to be consistent on Firefox on macOS oddly. Not sure how it could not be the serviceworker though when unregistering it will fix the issue until it gets re-registered?

**Comment by silviolleite** [comment]
The default serviceworker.js works by listening for the response, and if the response status code is 200, then it will register a new cache, if NOT, call the page offline. The problem may be in the browser cache. I am sending a link to you about the serviceworker and hope this can help you [https://developers.google.com/web/fundamentals/primers/service-workers/](https://developers.google.com/web/fundamentals/primers/service-workers/)

**Comment by pnaylor** [comment]
Not sure how this got originated still, but seem to have been able to get around it by clearing the site storage cache.

**Comment by VivienGiraud** [comment]
Hi,
We run into the same issue. 
If LOGOUT_REDIRECT_URL is set to "/" Django will make a 302 and then the /offline template is rendered. But if I remove it I haven't the issue anymore.
Any idea how to make django-pwa handle 200 and 302 ?

**Comment by VivienGiraud** [comment]
BTW my logout url is like that:
`url(r'^logout/(?P<next_page>.*)/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
`

**Comment by VivienGiraud** [comment]
OK I found the issue.
I was using :
`self.addEventListener('fetch', function(event) {
  var requestUrl = new URL(event.request.url);
    if (requestUrl.origin === location.origin) {
      if ((requestUrl.pathname === '/')) {
        event.respondWith(caches.match('/offline/'));
        return;
      }
    }
    event.respondWith(
      caches.match(event.request).then(function(response) {
        return response || fetch(event.request);
      })
    );
});
`
Instead of the original
`self.addEventListener("fetch", event => {
    event.respondWith(
        caches.match(event.request)
            .then(response => {
                return response || fetch(event.request);
            })
            .catch(() => {
                return caches.match('/offline/');
            })
    )
});`
I have no idea why I did this...
Thanks goes to the rubber duck!

**Comment by Olfredos6** [comment]
Had to remove the entire content inside the **fetch** callback function to stop running into this issue. Guess I need some more reading in order to understand how this really works
