### ISSUE TITLE
in Django 3: ImportError: cannot import name 'url' from 'django.urls' 

### ISSUE THREAD

**Issue by realjoselara** [silviolleite/django-pwa#36]
from django.urls import url

 url('', include('pwa.urls')),  # You MUST use an empty string as the URL prefix

 from django.urls import path, url
ImportError: cannot import name 'url' from 'django.urls' 

any workaround? I tried using path, and re_path and nothing

**Comment by Natureshadow** [comment]
`path('', include('pwa.urls'))` works perfectly.

**Comment by realjoselara** [comment]
That didnt' work either: 
    
path('', include('pwa.urls')),

    raise ImproperlyConfigured(msg.format(name=self.urlconf_name))
django.core.exceptions.ImproperlyConfigured: The included URLconf 'santuariosite.urls' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.

**Comment by Natureshadow** [comment]
Then this is a duplicate of #34.

**Comment by realjoselara** [comment]
Version 1.0.8 fixes this! thank you :)
