### ISSUE TITLE
ModuleNotFoundError: No module named 'pwa'

### ISSUE THREAD

**Issue by joaquinacuna** [silviolleite/django-pwa#42]
hi, i have the error in the issue name, i have 
Successfully installed asgiref-3.2.7 django-3.0.6 django-pwa-1.0.8 pytz-2020.1 sqlparse-0.3.1

**Comment by Smyja** [comment]
> 
> 
> hi, i have the error in the issue name, i have
> Successfully installed asgiref-3.2.7 django-3.0.6 django-pwa-1.0.8 pytz-2020.1 sqlparse-0.3.1

did you find a solution?

**Comment by joaquinacuna** [comment]
Yes! i just have to add PWA to my pycharm interpreter, sorri! TY!
