### ISSUE TITLE
Uncaught (in promise) TypeError: Request failed Fix!

### ISSUE THREAD

**Issue by josylad** [silviolleite/django-pwa#49]
Hello, 
what is the solution to this Uncaught (in promise) TypeError: Request failed issue??

My PWA is not working in production due to this error.

**Comment by josylad** [comment]
When I visit /offline/ 
I get a 400 bad request!

**Comment by josylad** [comment]
I have fixed it.

**Comment by Ivanrputra** [comment]
how u fix this?

**Comment by josylad** [comment]
> how u fix this?

I fixed this by creating a customer service worker file; the problem was in the 
``` var filesToCache = [ ];  ```

there were lots of files that couldn't be found in the filesToCache list.
