### ISSUE TITLE
QUESTION: exists any tutorial real projects like blog or todo list??

### ISSUE THREAD

**Issue by CARocha** [silviolleite/django-pwa#50]
Hi, exist any tutorial for this app??

**Comment by silviolleite** [comment]
Yes! In this repository [django-pwa-demo](https://github.com/silviolleite/django-pwa-demo)

**Comment by CARocha** [comment]
@silviolleite yes i see but this projects is very simple not used databases, any persistence storage
any models nothing https://github.com/silviolleite/django-pwa-demo/blob/master/project/core/models.py

Maybe I'm confused but I wanted an example with a real web with databases or api connection is possible?
or just by installing the app, would everything work well? or I need to do something else??
