### ISSUE TITLE
Not Found: /css/django-pwa-app.css

### ISSUE THREAD

**Issue by stefanbschneider** [silviolleite/django-pwa#57]
I'm struggling to get `django-pwa` to work properly. I followed the setup steps and verified that `/manifest.json` and `/serviceworker.js` are served.

However, I still think it's not working like a proper PWA, yet. For example, [I still don't get the "add to homescreen" popup](https://github.com/silviolleite/django-pwa/issues/56).

Also, I just noticed that I always get an error: `Not Found: /css/django-pwa-app.css` - whether I use the default `serviceworker.js` or a custom one.
Is the configured CSS path wrong? Or do I need to provide my own CSS? I thought this comes with `django-pwa`? What about the `/offline` page?

**Comment by jackbransfield** [comment]
Hello, just wondering if you got a resolution to this in the end? I am experiencing the same problem. Thanks in advance!

**Comment by quroom** [comment]
> Hello, just wondering if you got a resolution to this in the end? I am experiencing the same problem. Thanks in advance!

I faced same issue.
In my case, it's related to browser policy whether showing popup or not by thier logical rule.
So I tested with another browser, whale.
It works fine.
