### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by justin-ven** [silviolleite/django-pwa#6]
Tried djanog-pwa today, and found that the service worker would not register.  Investigations suggest that the cause is re-directs generated by i18n (from root to, e.g. /en/).

**Comment by silviolleite** [comment]
Hello @justin-ven I am sorry I was very busy last month. The new release v1.0.5 supports the `scope` in `manifest.json` and `serviceworker.js`, I think it can help you. Further details in `README.md`.
