### ISSUE TITLE
Not Installing as webapks

### ISSUE THREAD

**Issue by programmersidharth** [silviolleite/django-pwa#62]
Hey guys!
I've been using this on my website [https://sidtu.be](https://sidtu.be) 
My Website is HTTPS!
it only installs my website on home screen...
But I've seen a lot of website installing it as webapk

it also doesn't show add to home screen button, In android I have to go and click add to home screen by clicking those three dots in top right corner...
In Desktop I have no way to install the app!

you can go and see my website and please tell me how can I do it!

**Comment by elementzonline** [comment]
@programmersidharth 

I was able to tackle this issue of missing install the app in Chrome.  Made a pull request with the changes  I made. 
In Android, it didn't present the Install app option on top of the web app. Instead, I had to install it to the Home screen from Menu as you mentioned. 

https://github.com/silviolleite/django-pwa/pull/63

Basically, you need to check the Inspect Element -> Application -> Manifest, to see if there are any issues with the manifest file generated by the PWA application.

**Comment by programmersidharth** [comment]
thanks!
Now I'm able to created PWA apps.
https://sidtu.be check it out its a social networking platform built using Django and now its PWA is ready!
