### ISSUE TITLE
Issue with precaching during sw install

### ISSUE THREAD

**Issue by pnaylor** [silviolleite/django-pwa#9]
I have `{% load pwa %}` in my base template and want it to get installed only for logged in users so pages and assets can authenticate and cache properly. My login page does not extend the base template, but the serviceworker still seems to get installed on this page anyway, which causes the precaching to fail due to unauthenticated requests.

Any ideas for how to handle this situation properly? Why is it getting installed on a page that doesn't include the `load pwa` directive? Anything else I can do to work around this?

Thanks, hoping this plugin will help with my Django pwa project!

**Comment by silviolleite** [comment]
Hello @pnaylor ... I had updated the lib and it is supporting the `scope` options to `manifest.json` and  `serviceworker.js` on release v1.0.5
 
I think that article can help you too >>> https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle
