### ISSUE TITLE
How to solve compatibility with django 4.

### ISSUE THREAD

**Issue by GEORGES-DTECH** [silviolleite/django-pwa#91]
Go into the installed pwa app in your  urls.Its using regular expressions instead of path(...).
change it to use path as shown below:

from django.urls import path
from .views import manifest, service_worker

urlpatterns = [
    path('serviceworker.js/', service_worker),
    path('manifest.json', manifest)
]

**Comment by dhenderson** [comment]
@GEORGES-DTECH exactly what I needed, thanks for this.

**Comment by GEORGES-DTECH** [comment]
You welcome

**Comment by hartungstenio** [comment]
Hello. I will close this issue. Let's focus discussions in #83

**Comment by GEORGES-DTECH** [comment]
Good,if you solved it.
